language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e .
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test --doctest-modules --pep8 resuds -v --cov resuds --cov-report term-missing
