<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns3:GetFlightListResponse xmlns:ns3="http://Amobee.com/" xmlns:ns2="http://Amobee.com/Common/Schema"><FlightList><Flight Id="35070557" Name="Appsfuel test" CampaignId="35070539" MediaChannelId="2" FormatId="300" ResourceTypeId="2" RunOfNetwork="true" State="APPROVED" SupportCompanionFlights="false" CompanionFlight="false" PercentageWeighting="false"><AdspaceIdList/><ExcludedAdspaceIdList/><CategoryIdList/><ContextualCategoryIdList/><TimeTargeting StartDate="2013-01-15T23:00:00.000Z" EndDate="2013-09-30T21:59:00.000Z"><TimeTargetingValueList/></TimeTargeting><UserFrequencyCapList/><DeliveryInfo Priority="NORMAL"/><TargetedAttributeList/><GeoTargetingList/><FlightAdList><FlightAd Id="35070558" adId="35070556" State="ACTIVE" Weight="10"/></FlightAdList></Flight></FlightList></ns3:GetFlightListResponse></soap:Body></soap:Envelope>