<wsdl:definitions targetNamespace="http://Amobee.com/"
                  xmlns:tns="http://Amobee.com/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/">

    <wsdl:import namespace="http://Amobee.com/Inventory/" location="inventory.wsdl"/>

    <wsdl:service name="InventoryService">
        <wsdl:port name="Inventory" binding="tns:InventoryWSSoap">
            <soap:address location="https://appsfuelweb.amobee.com/invetory"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
