<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns3:GetAdSpaceResponse xmlns:ns3="http://Amobee.com/" xmlns:ns2="http://Amobee.com/Common/Schema"><Adspace Id="32645" ExternalId="32644" Name="new Adspace12" PublisherId="35070528" MediaChannelId="2" Active="true" LongTail="false" EstDailyUsers="1" EstDailyImps="1" AllowCompanionFlights="false" Test="false" SupportConvTracking="false"><FormatResourceTypeList><FormatResourceType FormatId="300"><ResourceTypeIdList><EntityId>2</EntityId><EntityId>1</EntityId></ResourceTypeIdList></FormatResourceType></FormatResourceTypeList><CategoryIdList/><ExcludedTopicIdList/></Adspace></ns3:GetAdSpaceResponse></soap:Body></soap:Envelope>
